consumables/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = patterns('',
    url(r'^api/(?P<pk>\d+)/$', views.ItemDetail.as_view(), name='api_list'),
    url(r'^api/$', views.ItemList.as_view(), name='api_detail'),

    url(r'^$', views.ItemListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)', views.ItemDetailView.as_view(), name='detail' ),
    url(r'^(?P<slug>[\w-]+)', views.ItemDetailView.as_view(), name='detail' ),
)

urlpatterns = format_suffix_patterns(urlpatterns)

gw2cons/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gw2cons.views.home', name='home'),
    # url(r'^gw2cons/', include('gw2cons.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('consumables.urls', namespace='consumables'))
)

consumables/models.py
from django.db import models
from django.template.defaultfilters import slugify

def convert_cost(cost):
    if (cost is None):
        return '0'
    elif (cost > 9999):
        return '%sg %ss %sc' % (cost / 10000 , (cost % 10000) / 100, cost % 100)
    elif (cost > 99):
        return '%ss %sc' % (cost / 100, cost % 100)
    else:
        return '%sc' % cost

class Item(models.Model):

    CONSUMABLE_TYPES = (
        ('FOOD', 'Food'),
        ('UTIL', 'Utility'),
    )

    name = models.CharField(max_length=255)
    duration = models.IntegerField()
    required_level = models.IntegerField()
    buy_cost = models.IntegerField(blank=True, null=True)
    sell_cost = models.IntegerField(blank=True, null=True)
    consumable_type = models.CharField(max_length=32)
    slug = models.SlugField(max_length=255, blank=True, default='')
    description = models.TextField()
    last_updated = models.DateTimeField(auto_now=True)

    def get_duration_minutes(self):
        return "%s m" % (int(self.duration) / 60000)

    def get_buy_cost(self):
        return convert_cost(self.buy_cost)

    def get_sell_cost(self):
        return convert_cost(self.sell_cost)

    def __unicode__(self):
        return self.name

    def __save__(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ("consumables:detail", (), {"slug": self.slug})

class Stat(models.Model):
    name = models.CharField(max_length=255)
    items = models.ManyToManyField(Item, through="Item_Stat")

    def __unicode__(self):
        return self.name

class Item_Stat(models.Model):
    item = models.ForeignKey(Item)
    stat = models.ForeignKey(Stat)
    magnitude = models.CharField(max_length=64, default='0')
    order_number = models.IntegerField()

    def __unicode__(self):
        return '%s: %s %s' % (self.item, self.magnitude, self.stat)

consumables/views.py
from .models import Item, Stat
from django.views.generic import ListView, DetailView, TemplateView

from rest_framework import viewsets
from .serializers import ItemSerializer

from rest_framework.mixins import ListModelMixin, RetrieveModelMixin
from rest_framework.generics import GenericAPIView

class ItemListView(ListView):
    model = Item
    template_name = "item_list.html"


class ItemDetailView(DetailView):
    model = Item
    template_name = "item_detail.html"

class ItemList(ListModelMixin, GenericAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

class ItemDetail(RetrieveModelMixin, GenericAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

consumables/templates/consumables/item_detail.html
{% extends "_layouts/base.html" %}

{% block page_title %}{{ item.name }} | {% endblock %}

{% block page_content %}
<h2>{{ item.name }}</h2><br/>
Buycost: {{ item.get_buy_cost }}<br/>
Sellcost: {{ item.get_sell_cost }}<br/>
{% for item_stat in item.item_stat_set.all %}
    {{ item_stat.stat.name }}: {{ item_stat.magnitude }}<br/>
{% endfor %}
<p><a href="{% url 'consumables:list' %}">Item List</a></p>
{% endblock %}

consumables/templates/consumables/item_list.html
{% extends "_layouts/base.html" %}

{% block page_title %}Items | {% endblock %}

{% block custom_assets %}
<link rel="stylesheet" href="{{ STATIC_URL }}font-awesome/css/font-awesome.css" />
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-2.0.3.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.dataTables.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $.extend($.fn.dataTable.defaults, {
           "bInfo": false
        });
        $("#item-table").dataTable( {
           "sPaginationType": "full_numbers",
           "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
        });
    });
</script>
<style>
    a.paginate_button, a.paginate_active {
        cursor: pointer;
        padding: 4px 12px;
        border: 1px solid #dddddd;
        border-left-width: 0;
        text-decoration: none;
    }
    a.paginate_button {
        background-color: #ffffff;
    }
    a.paginate_active {
        background-color: #f5f5f5;
        color: #999999;
    }
    a.paginate_button.first{
        -webkit-border-bottom-left-radius: 5px;
        border-bottom-left-radius: 5px;
        -webkit-border-top-left-radius: 5px;
        border-top-left-radius: 5px;
        border-left-width: 1px;
    }
    a.paginate_button.last{
        -webkit-border-bottom-right-radius: 5px;
        border-bottom-right-radius: 5px;
        -webkit-border-top-right-image: 5px;
        border-top-right-radius: 5px;
    }

    .dataTables_paginate {
        text-align: center;
    }
    #item-table_length {
        float: left;
    }
    #item-table_filter {
        float: right;
    }
    .sorting_asc:after {
        font-family: FontAwesome;
        content: "\f0de";
    }
    .sorting_desc:after {
        font-family: FontAwesome;
        content: "\f0dd";
    }
    thead:hover {
        cursor: pointer;
    }

</style>
{% endblock %}

{% block page_content %}

    <table id="item-table" class="table table-bordered table-hover">
        <thead><tr>
            <th>Name</th>
            <th>Level</th>
            <th>Duration</th>
            <th>Buy</th>
            <th>Sell</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        {% for item in item_list %}
        <tr>
            <td><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></td>
            <td>{{ item.required_level }}</td>
            <td>{{ item.get_duration_minutes }}</td>
            <td><div class="gw2-currency">{{ item.buy_cost }}</div></td>
            <td>{{ item.sell_cost }}</td>
            <td>{{ item.description | linebreaks }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/_layouts/base.html
<!doctype html>
<html>
    <head>
        <title>{% block page_title %}{% endblock %}GW2 Consumables</title>
        <link href="{{ STATIC_URL }}bootstrap.min.css" rel="stylesheet">
        <style>
          body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
          }
        </style>
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="../assets/js/html5shiv.js"></script>
        <![endif]-->
        {% block custom_assets %} {% endblock %}
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <a class="brand" href="/">GW2 Consumables</a>
            </div>
          </div>
        </div>
        <div class="container">
        {% block page_content %}{% endblock %}

        <hr />

        </div>
    <div id="push"></div>
    </div>
    <div id="footer">
      <div class="container">
        <p class="muted credit"><a href="https://github.com/menglewis/gw2cons" target="_blank">An open source project</a></p>
      </div>
    </div>
    </body>

</html>